services:
  api:
    image: rusdog2784/mile-high-aerials-api:latest
    restart: always
    container_name: mile-high-aerials-api
    volumes:
      - ./keys/mile-high-aerials-server-sa.json:/app/server-sa.json
    environment:
      - DEBUG=0
    ports:
      - "8888:8080"
    depends_on:
      - redis
  client:
    image: rusdog2784/mile-high-aerials-client:latest
    restart: always
    container_name: mile-high-aerials-client
    volumes:
      - ./logs/nginx/mile-high-aerials.client.access.log:/var/log/nginx/mile-high-aerials.client.access.log
      - ./logs/nginx/mile-high-aerials.client.error.log:/var/log/nginx/mile-high-aerials.client.error.log
    ports:
      - "80:8080"
  redis:
    image: redislabs/redismod
    restart: always
    container_name: mile-high-aerials-redis
