version: '3'
services:
  flask_server:
    build: ./server
    container_name: mile-high-aerials-server
    volumes:
      - ./keys/mile-high-aerials-server-sa.json:/app/server-sa.json
    environment:
      - DEBUG=1
    ports:
      - "8080:8080"
    depends_on:
      - redis-cache
  
  redis-cache:
    image: redislabs/redismod
    ports:
      - '6379:6379'

  nginx_website:
    build: ./client
    container_name: mile-high-aerials-client
    ports:
      - "80:8080"
