name: Build and Push Docker Images
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 and trying to push the client and api images to DockerHub
on:
  push:
    branches:
      - main
jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  # Should be a Personal Access Token

      - name: Build and push client image
        run: |-
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mile-high-aerials-client:prod --platform linux/amd64 -f Dockerfile.prod ./client
          docker push ${{ secrets.DOCKER_USERNAME }}/mile-high-aerials-client:latest
      
      - name: Build and push api image
        run: |-
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mile-high-aerials-api:prod --platform linux/amd64 -f Dockerfile.prod ./server
          docker push ${{ secrets.DOCKER_USERNAME }}/mile-high-aerials-api:latest
      
